# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a0c0ddebe76790623263578332e47ae377f5ab6f443bfb1e6d9205c814bc25916f258b6c1157f6a4de2fb8af6d562630f1a6182b9a4c7cf4012adedb24f825

test:
  secret_key_base: b8ca06bae75b6a7ec0111ad1c87e2e6caa3a751fff4cedf02a9fa9611e9ca2c1e73e387dea4aff1fd8343430968b6980d9b9cd029fd271776d14f56ba4c9a4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
